# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: "Contact"
    url: 'https://manoahawaiiss.az1.qualtrics.com/jfe/form/SV_emKHsDXKGkyiME6'
    weight: 70
  - name: "CV"
    url: 'cv/cv.pdf'
    weight: 150
